spring.application.name=nhom12

# Server
server.port=8080

# MongoDB
spring.data.mongodb.uri=mongodb+srv://quangvinh02200_db_user:3rgv230nrZNBudpa@cluster0.tlwmnuk.mongodb.net/nhom12?appName=Cluster0
spring.data.mongodb.auto-index-creation=true

# JWT
jwt.secret=nhom12-super-secret-key-must-be-at-least-256-bits-long-for-hs256
jwt.expiration=86400000

# Jackson
spring.jackson.default-property-inclusion=NON_NULL

# MoMo Payment Gateway
momo.partner-code=MOMOBKUN20180529
momo.access-key=klm05TvNBzhg7h7j
momo.secret-key=at67qH6mk8w5Y1nAyMoYKMWACiEi2bsa
momo.api-url=https://test-payment.momo.vn/v2/gateway/api/create
momo.ipn-url=http://localhost:8080/momo/ipn
momo.redirect-url=http://localhost:8080/momo/return
